import { Box, Stack } from "@mui/material";
import { useEffect } from "react";

export default function Work() {
    useEffect(() => {
        window.scrollTo({top: 0});
    }, []);

    return (
        <Stack>
            <Box fontWeight={700}>Title</Box>
            <Box fontSize="0.875rem" color="#999" mb={1} >August 12th, 2022</Box>
            <Box>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem fringilla ut morbi tincidunt augue. Tristique senectus et netus et malesuada fames ac turpis. Cursus in hac habitasse platea dictumst quisque sagittis purus. Donec adipiscing tristique risus nec. Mauris nunc congue nisi vitae suscipit. Lobortis feugiat vivamus at augue eget arcu dictum varius. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Dolor morbi non arcu risus quis varius quam quisque. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. In hendrerit gravida rutrum quisque non tellus orci ac. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Diam maecenas sed enim ut sem viverra aliquet eget sit. Amet venenatis urna cursus eget. Eu turpis egestas pretium aenean.
                Consequat semper viverra nam libero justo laoreet sit amet cursus. Eget nunc scelerisque viverra mauris in aliquam. Libero justo laoreet sit amet cursus sit amet. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Amet cursus sit amet dictum sit amet. Ac tortor vitae purus faucibus ornare suspendisse. In fermentum et sollicitudin ac orci. Neque gravida in fermentum et sollicitudin ac. Scelerisque viverra mauris in aliquam. Accumsan sit amet nulla facilisi morbi. Ornare lectus sit amet est. Id diam maecenas ultricies mi. Turpis egestas integer eget aliquet nibh. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Pharetra pharetra massa massa ultricies mi. Neque convallis a cras semper auctor.
                Sollicitudin aliquam ultrices sagittis orci. Vitae semper quis lectus nulla at volutpat. Nibh cras pulvinar mattis nunc sed blandit libero. Purus semper eget duis at. Orci phasellus egestas tellus rutrum. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Tincidunt ornare massa eget egestas purus. Elementum nisi quis eleifend quam adipiscing. Cras sed felis eget velit. Aenean pharetra magna ac placerat vestibulum. Felis eget nunc lobortis mattis aliquam faucibus purus. Feugiat in ante metus dictum at tempor commodo ullamcorper.
                Ornare quam viverra orci sagittis eu. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Pellentesque id nibh tortor id aliquet lectus proin nibh. Eu scelerisque felis imperdiet proin fermentum leo vel. Mi tempus imperdiet nulla malesuada pellentesque elit eget. In massa tempor nec feugiat nisl pretium fusce. Sagittis vitae et leo duis ut diam quam. Dui faucibus in ornare quam viverra. Dolor purus non enim praesent elementum facilisis leo. Ut eu sem integer vitae justo eget magna fermentum. Ornare quam viverra orci sagittis eu. In cursus turpis massa tincidunt dui ut ornare lectus sit. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Pharetra et ultrices neque ornare aenean euismod. Nisl nisi scelerisque eu ultrices.
                Purus in mollis nunc sed id semper risus in. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Convallis posuere morbi leo urna molestie at. Suspendisse potenti nullam ac tortor vitae purus. Vulputate odio ut enim blandit volutpat maecenas. Egestas pretium aenean pharetra magna ac placerat vestibulum. Massa id neque aliquam vestibulum morbi. Augue ut lectus arcu bibendum at varius. Ornare quam viverra orci sagittis eu. Interdum velit euismod in pellentesque massa placerat duis. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Faucibus turpis in eu mi bibendum neque. Imperdiet sed euismod nisi porta. Fames ac turpis egestas maecenas. Morbi tristique senectus et netus et malesuada fames ac.
                Facilisis volutpat est velit egestas dui id ornare arcu odio. Nisl condimentum id venenatis a. Ultricies integer quis auctor elit sed vulputate mi sit. Sed faucibus turpis in eu mi. Eros donec ac odio tempor orci dapibus ultrices. At in tellus integer feugiat scelerisque varius morbi enim nunc. Blandit turpis cursus in hac habitasse platea dictumst. Amet nisl purus in mollis nunc sed. Ut venenatis tellus in metus vulputate. Lectus urna duis convallis convallis. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin.
                Massa sed elementum tempus egestas. Eros in cursus turpis massa tincidunt dui ut ornare lectus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Sed faucibus turpis in eu mi bibendum neque egestas. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Libero nunc consequat interdum varius sit amet. Aliquet enim tortor at auctor urna nunc id. Neque convallis a cras semper auctor. Nascetur ridiculus mus mauris vitae. Vulputate dignissim suspendisse in est ante in nibh. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu non sodales neque sodales ut etiam. Tincidunt nunc pulvinar sapien et ligula. Amet volutpat consequat mauris nunc congue. Egestas dui id ornare arcu. Amet est placerat in egestas erat.
                Lorem donec massa sapien faucibus. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Duis at consectetur lorem donec massa. Vivamus arcu felis bibendum ut tristique et. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Congue eu consequat ac felis donec. Vivamus at augue eget arcu dictum varius duis at. Fringilla ut morbi tincidunt augue interdum velit euismod. Est ante in nibh mauris. Risus pretium quam vulputate dignissim. Sem viverra aliquet eget sit amet. Mauris augue neque gravida in. Nisl rhoncus mattis rhoncus urna neque viverra justo. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.
                Orci porta non pulvinar neque laoreet suspendisse interdum. Nunc id cursus metus aliquam eleifend. Urna neque viverra justo nec ultrices dui sapien eget mi. Volutpat commodo sed egestas egestas. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Massa enim nec dui nunc mattis. Scelerisque in dictum non consectetur a erat. Non blandit massa enim nec dui nunc mattis enim ut. Tristique risus nec feugiat in. Morbi tincidunt augue interdum velit. Semper risus in hendrerit gravida rutrum quisque non. Nisi scelerisque eu ultrices vitae auctor eu augue. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Interdum velit laoreet id donec ultrices tincidunt arcu non. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Porta lorem mollis aliquam ut porttitor leo a. Orci ac auctor augue mauris augue.
                Lectus urna duis convallis convallis tellus id interdum velit. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. In pellentesque massa placerat duis. Congue quisque egestas diam in arcu cursus euismod quis. Urna nunc id cursus metus aliquam eleifend mi in. Ante metus dictum at tempor commodo. Eget duis at tellus at. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Tellus mauris a diam maecenas sed enim. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Eu augue ut lectus arcu bibendum at varius vel pharetra.

                Enim diam vulputate ut pharetra sit amet aliquam. In hac habitasse platea dictumst. Nibh sed pulvinar proin gravida hendrerit lectus. Interdum varius sit amet mattis vulputate enim nulla. Sit amet facilisis magna etiam tempor orci eu. Viverra ipsum nunc aliquet bibendum enim. Ac turpis egestas integer eget. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Nisl suscipit adipiscing bibendum est ultricies integer quis. Massa sed elementum tempus egestas sed. Duis convallis convallis tellus id interdum velit laoreet id. Ullamcorper eget nulla facilisi etiam dignissim. Eget nulla facilisi etiam dignissim diam. Placerat in egestas erat imperdiet sed euismod. Quam pellentesque nec nam aliquam sem et tortor. Magna etiam tempor orci eu lobortis elementum. Vulputate ut pharetra sit amet aliquam id diam maecenas.

                Urna condimentum mattis pellentesque id nibh tortor. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Et malesuada fames ac turpis egestas sed tempus. Neque viverra justo nec ultrices dui sapien eget mi proin. Viverra aliquet eget sit amet tellus cras adipiscing enim. Vitae justo eget magna fermentum iaculis eu non. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Dignissim sodales ut eu sem integer. Magna sit amet purus gravida quis blandit. Euismod lacinia at quis risus sed vulputate. In vitae turpis massa sed elementum tempus egestas. Purus sit amet luctus venenatis lectus magna. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Purus ut faucibus pulvinar elementum integer. Faucibus purus in massa tempor nec feugiat. Duis at tellus at urna condimentum mattis pellentesque id nibh. Ultricies integer quis auctor elit sed. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed.

                Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Dui vivamus arcu felis bibendum. Aliquet risus feugiat in ante metus dictum at tempor. Quam id leo in vitae. Risus feugiat in ante metus dictum. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Turpis massa sed elementum tempus egestas sed. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Sed odio morbi quis commodo odio aenean sed adipiscing. Sapien nec sagittis aliquam malesuada bibendum. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus.

                Tellus molestie nunc non blandit massa. Tempor nec feugiat nisl pretium fusce id. Nulla pellentesque dignissim enim sit. Nulla facilisi cras fermentum odio. Gravida cum sociis natoque penatibus et magnis dis. Eu non diam phasellus vestibulum lorem sed risus. Lorem dolor sed viverra ipsum nunc. Placerat in egestas erat imperdiet sed euismod nisi. Et netus et malesuada fames ac turpis. Amet massa vitae tortor condimentum lacinia quis. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Amet risus nullam eget felis eget nunc lobortis mattis. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Non nisi est sit amet facilisis magna. Eget dolor morbi non arcu risus quis varius. Id interdum velit laoreet id donec ultrices tincidunt arcu. Consequat id porta nibh venenatis cras sed felis eget. Consectetur adipiscing elit ut aliquam purus sit. Nec feugiat in fermentum posuere urna nec.

                Posuere morbi leo urna molestie at elementum eu facilisis. In vitae turpis massa sed elementum. Porttitor eget dolor morbi non arcu risus. Dui vivamus arcu felis bibendum ut tristique et. Nunc non blandit massa enim. Nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis. At in tellus integer feugiat scelerisque varius morbi enim. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Nibh ipsum consequat nisl vel pretium lectus. Vitae suscipit tellus mauris a diam maecenas sed enim. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Ut tellus elementum sagittis vitae et leo duis ut diam. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Consequat semper viverra nam libero justo laoreet. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Faucibus in ornare quam viverra orci sagittis eu volutpat odio.

                Erat velit scelerisque in dictum non consectetur a erat. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Dui accumsan sit amet nulla. Vel pharetra vel turpis nunc. Egestas erat imperdiet sed euismod nisi porta lorem. Quam quisque id diam vel. Vel orci porta non pulvinar neque laoreet. Ipsum a arcu cursus vitae congue. Lobortis feugiat vivamus at augue eget arcu. Suspendisse sed nisi lacus sed viverra tellus. Nulla porttitor massa id neque. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Quisque sagittis purus sit amet volutpat. Orci ac auctor augue mauris.

                Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Vestibulum morbi blandit cursus risus. Pulvinar pellentesque habitant morbi tristique senectus et netus. Ut tristique et egestas quis ipsum suspendisse ultrices. Tristique senectus et netus et malesuada fames. Sed felis eget velit aliquet sagittis id consectetur purus ut. In ante metus dictum at tempor commodo ullamcorper a. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Accumsan in nisl nisi scelerisque eu ultrices vitae. Turpis nunc eget lorem dolor sed viverra ipsum.

                Eu mi bibendum neque egestas congue. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Nisl vel pretium lectus quam id leo in. Orci sagittis eu volutpat odio facilisis. Aliquam faucibus purus in massa tempor nec feugiat. Adipiscing vitae proin sagittis nisl rhoncus mattis. Nulla aliquet porttitor lacus luctus accumsan. Pellentesque pulvinar pellentesque habitant morbi. Netus et malesuada fames ac turpis egestas integer eget. Tellus pellentesque eu tincidunt tortor aliquam. Eget sit amet tellus cras. Convallis a cras semper auctor neque vitae tempus. Quis commodo odio aenean sed adipiscing. A erat nam at lectus urna duis. Malesuada pellentesque elit eget gravida cum sociis natoque. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Mauris pharetra et ultrices neque ornare. Massa ultricies mi quis hendrerit dolor magna.

                Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Augue mauris augue neque gravida in fermentum et sollicitudin. Elementum sagittis vitae et leo duis ut diam quam. Placerat orci nulla pellentesque dignissim enim sit. Adipiscing elit pellentesque habitant morbi tristique. Sed euismod nisi porta lorem. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Leo vel fringilla est ullamcorper eget nulla facilisi.

                Venenatis a condimentum vitae sapien pellentesque. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Tellus at urna condimentum mattis pellentesque id nibh. Urna et pharetra pharetra massa massa ultricies. Orci nulla pellentesque dignissim enim sit. Sem et tortor consequat id porta nibh venenatis. Viverra justo nec ultrices dui sapien eget mi proin. Non diam phasellus vestibulum lorem sed. Quis vel eros donec ac odio tempor orci dapibus ultrices. Aliquet nec ullamcorper sit amet risus nullam eget. Senectus et netus et malesuada fames. Netus et malesuada fames ac turpis. Lorem ipsum dolor sit amet consectetur adipiscing. Nulla facilisi etiam dignissim diam quis. Adipiscing diam donec adipiscing tristique risus nec feugiat. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Adipiscing elit pellentesque habitant morbi tristique. Donec ac odio tempor orci.
            </Box>
        </Stack>
    );
}